//! Race and class flavour text, read at runtime from the user's own `game.dll`.
//!
//! # Why here and not in the repo
//!
//! The creation form's two description panes (`race_desc_label_text`, `class_desc_label_text` in
//! `pregame/character_creation.xml`) are fed by prose that exists in exactly one place: the client's
//! `game.dll`. It is not in any `.mpk`/`.npk` in the client tree, not in DOL's source, not in its
//! 44 MB database dump, and not in its language files — all four were searched exhaustively.
//!
//! So CAER reads it the same way it reads every other client asset: from the file the user already
//! has, at runtime, shipping nothing. `data/desc_offsets.toml` holds **byte offsets only**.
//!
//! # Fail-closed
//!
//! The offsets are specific to one `game.dll` build, so the table records that build's sha256.
//! A different build yields [`DescriptionTable::empty`] and the panes render blank — the same state
//! as before this module existed. Nothing is guessed and no substitute text is invented.

use std::collections::HashMap;
use std::path::Path;

/// Offsets + the build they were taken from. Generated by `tools/extract_desc_offsets.py`.
const OFFSETS_TOML: &str = include_str!("../data/desc_offsets.toml");

/// A description longer than this is a parse error, not a description.
const MAX_DESCRIPTION_LEN: usize = 2048;

/// Resolved flavour text, keyed by the same ids `caer_protocol::career` uses.
#[derive(Debug, Clone, Default)]
pub struct DescriptionTable {
    race: HashMap<u8, String>,
    class: HashMap<u8, String>,
    /// Whether the client build matched the offsets' recorded build.
    verified: bool,
    /// Races this client has patched out of its own binary — see [`Offsets::absent_race`].
    absent_race: Vec<u8>,
}

impl DescriptionTable {
    /// No descriptions — an unrecognised client build, or no client at all.
    #[must_use]
    pub fn empty() -> Self {
        Self::default()
    }

    /// Has this client deliberately removed the description for `race`?
    ///
    /// `true` means the prose is not in the player's binary to read, so the pane is blank for a
    /// reason. It says nothing about whether the race is playable: DOL carries the Minotaur and so
    /// does CAER — the button, the body and the living model are all unaffected.
    #[must_use]
    pub fn is_absent_race(&self, race: u8) -> bool {
        self.absent_race.contains(&race)
    }

    /// Flavour text for a race id, or `None` when unavailable.
    #[must_use]
    pub fn race(&self, race_id: u8) -> Option<&str> {
        self.race.get(&race_id).map(String::as_str)
    }

    /// Flavour text for a class id, or `None` when unavailable.
    #[must_use]
    pub fn class(&self, class_id: u8) -> Option<&str> {
        self.class.get(&class_id).map(String::as_str)
    }

    /// True when the offsets were read from the exact build they were generated against.
    #[must_use]
    pub fn is_verified(&self) -> bool {
        self.verified
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.race.len() + self.class.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

/// One `id = 0xOFFSET` row from the generated table.
type OffsetRow = (u8, usize);

/// What the generated table records: the `game.dll` it was cut from, and where each race and class
/// blurb starts inside it.
struct Offsets {
    game_dll_sha256: String,
    race: Vec<OffsetRow>,
    class: Vec<OffsetRow>,
    /// Ids this build has patched OUT of its binary, declared rather than merely missing.
    ///
    /// A shard can overwrite a description in place — Eden replaces the Minotaur blurb with
    /// "This race is unavailable." — and the phrase is then genuinely not there to find. Naming
    /// those ids is what separates "this client does not carry it" from "the extractor missed
    /// one", which otherwise look identical from here and from a test.
    absent_race: Vec<u8>,
}

/// Every build the table carries.
///
/// **More than one client is legitimate.** A clean retail `game.dll` and a shard's patched copy are
/// different files with different layouts, and a player has whichever they have. A `game_dll_sha256`
/// line opens a new build block; blocks are matched by hash, so an unrecognised client still falls
/// through to blank panes and nothing is ever read from offsets that were not cut from it.
fn parse_offsets() -> Vec<Offsets> {
    let mut out: Vec<Offsets> = Vec::new();
    let (mut sha, mut race, mut class) = (String::new(), Vec::new(), Vec::new());
    let mut absent_race: Vec<u8> = Vec::new();
    let mut section = "";
    for line in OFFSETS_TOML.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(rest) = line.strip_prefix('[') {
            section = match rest.trim_end_matches(']') {
                "race" => "race",
                "class" => "class",
                _ => "",
            };
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let (key, value) = (key.trim(), value.trim());
        if key == "game_dll_sha256" {
            if !sha.is_empty() {
                out.push(Offsets {
                    game_dll_sha256: std::mem::take(&mut sha),
                    race: std::mem::take(&mut race),
                    class: std::mem::take(&mut class),
                    absent_race: std::mem::take(&mut absent_race),
                });
            }
            sha = value.trim_matches('"').to_string();
            section = "";
            continue;
        }
        if key == "absent_race" {
            absent_race = value
                .trim_matches(|c| c == '[' || c == ']')
                .split(',')
                .filter_map(|v| v.trim().parse::<u8>().ok())
                .collect();
            continue;
        }
        let (Ok(id), Some(hex)) = (key.parse::<u8>(), value.strip_prefix("0x")) else {
            continue;
        };
        let Ok(off) = usize::from_str_radix(hex, 16) else {
            continue;
        };
        match section {
            "race" => race.push((id, off)),
            "class" => class.push((id, off)),
            _ => {}
        }
    }
    if !sha.is_empty() {
        out.push(Offsets {
            game_dll_sha256: sha,
            race,
            class,
            absent_race,
        });
    }
    out
}

/// Read the null-terminated string at `off`, decoded the way the client's own fonts index it.
///
/// **Byte-identity, not UTF-8 and not ASCII-only.** The client stores this prose as CP1252 and its
/// bitmap font atlases assign one glyph cell per byte from `0x21` to `0xFF`
/// (`caer_assets::bitmapfont`), so `ui/fonts/button_12.tga` carries a real 3px right-quote cell at
/// index `0x92`. Mapping each byte straight to its Latin-1 `char` therefore lands on the client's
/// own glyph. Transcoding `0x92` to U+2019 would ask the atlas for a cell it does not have and
/// draw a blank where the apostrophe belongs; rejecting it outright — which this used to do —
/// blanks the whole pane for the two races whose text contains one.
///
/// Rejects anything unterminated, empty, over [`MAX_DESCRIPTION_LEN`], or carrying a control byte:
/// those mean the offset did not land on a description and the result must not reach a player.
fn read_cstr(bytes: &[u8], off: usize) -> Option<String> {
    let rest = bytes.get(off..)?;
    let end = rest
        .iter()
        .take(MAX_DESCRIPTION_LEN)
        .position(|&b| b == 0)?;
    let raw = &rest[..end];
    if raw.is_empty() || raw.iter().any(|&b| b < 0x20 || b == 0x7f) {
        return None;
    }
    Some(raw.iter().map(|&b| char::from(b)).collect())
}

/// Load descriptions from `<client_root>/game.dll`.
///
/// Returns [`DescriptionTable::empty`] rather than an error when the file is absent or is a
/// different build: missing flavour text is a degraded screen, never a failed launch.
#[must_use]
pub fn load(client_root: &Path) -> DescriptionTable {
    let path = client_root.join("game.dll");
    let Ok(bytes) = std::fs::read(&path) else {
        log::info!(
            "caer-assets: no game.dll at {} — description panes will be blank",
            path.display()
        );
        return DescriptionTable::empty();
    };
    let builds = parse_offsets();
    let got_sha = sha256_hex(&bytes);
    let Some(offsets) = builds.iter().find(|b| b.game_dll_sha256 == got_sha) else {
        let known: Vec<&str> = builds
            .iter()
            .map(|b| &b.game_dll_sha256[..16.min(b.game_dll_sha256.len())])
            .collect();
        log::warn!(
            "caer-assets: game.dll is build {}, offsets are cut from {known:?} — \
             description panes will be blank rather than showing text from unverified offsets",
            &got_sha[..16.min(got_sha.len())]
        );
        return DescriptionTable::empty();
    };
    let (races, classes) = (offsets.race.clone(), offsets.class.clone());
    let mut table = DescriptionTable {
        verified: true,
        absent_race: offsets.absent_race.clone(),
        ..Default::default()
    };
    for (id, off) in races {
        if let Some(text) = read_cstr(&bytes, off) {
            table.race.insert(id, text);
        }
    }
    for (id, off) in classes {
        if let Some(text) = read_cstr(&bytes, off) {
            table.class.insert(id, text);
        }
    }
    log::info!(
        "caer-assets: loaded {} race + {} class descriptions from game.dll",
        table.race.len(),
        table.class.len()
    );
    table
}

/// Minimal SHA-256 so this module does not pull a hashing crate into `caer-assets`.
fn sha256_hex(data: &[u8]) -> String {
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];
    let mut msg = data.to_vec();
    let bitlen = (data.len() as u64).wrapping_mul(8);
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bitlen.to_be_bytes());
    for chunk in msg.chunks_exact(64) {
        let mut w = [0u32; 64];
        for (i, word) in chunk.chunks_exact(4).enumerate() {
            w[i] = u32::from_be_bytes([word[0], word[1], word[2], word[3]]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let (mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh) =
            (h[0], h[1], h[2], h[3], h[4], h[5], h[6], h[7]);
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let t1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        for (slot, v) in h.iter_mut().zip([a, b, c, d, e, f, g, hh]) {
            *slot = slot.wrapping_add(v);
        }
    }
    h.iter().map(|w| format!("{w:08x}")).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sha256_matches_known_vectors() {
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            sha256_hex(b"abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
    }

    /// The generated table must cover every race and advanced class, or a form pane silently
    /// renders blank for whatever was missed.
    #[test]
    fn offset_table_is_complete_and_well_formed() {
        let builds = parse_offsets();
        assert!(
            !builds.is_empty(),
            "the table must carry at least one build"
        );
        let mut seen: Vec<&str> = Vec::new();
        for b in &builds {
            assert_eq!(
                b.game_dll_sha256.len(),
                64,
                "recorded sha256 must be a full digest"
            );
            assert!(
                !seen.contains(&b.game_dll_sha256.as_str()),
                "two blocks claim build {} — the second would never be reached",
                b.game_dll_sha256
            );
            seen.push(&b.game_dll_sha256);
            assert_eq!(b.class.len(), 47, "47 advanced classes");
            // A shard may patch a race description out of its binary; every OTHER race must still
            // be there, so a silently half-read build cannot pass as a complete one.
            assert!(
                b.race.len() == 21 || b.race.len() == 18,
                "build {} carries {} races — 21, or 18 with the Minotaur trio patched out",
                &b.game_dll_sha256[..16],
                b.race.len()
            );
            for (id, off) in b.race.iter().chain(b.class.iter()) {
                assert!(*id > 0, "id 0 is not a valid race/class");
                assert!(*off > 0, "id {id} has a zero offset");
            }
        }
    }

    /// An unrecognised or absent client must yield no text rather than reading garbage.
    #[test]
    fn missing_client_fails_closed() {
        let t = load(Path::new("/nonexistent-client-root"));
        assert!(t.is_empty());
        assert!(!t.is_verified());
        assert_eq!(t.race(1), None);
        assert_eq!(t.class(2), None);
    }

    /// `read_cstr` must reject anything that is not a plausible description.
    #[test]
    fn read_cstr_rejects_non_descriptions() {
        assert_eq!(read_cstr(b"hello\0world", 0).as_deref(), Some("hello"));
        assert_eq!(read_cstr(b"\0", 0), None, "empty string");
        assert_eq!(read_cstr(b"no terminator", 0), None, "unterminated");
        assert_eq!(read_cstr(b"bad\x01byte\0", 0), None, "control byte");
        assert_eq!(read_cstr(b"del\x7fbyte\0", 0), None, "DEL is not text");
        assert_eq!(read_cstr(b"hello\0", 99), None, "out of range");
        let long = vec![b'a'; MAX_DESCRIPTION_LEN + 10];
        assert_eq!(read_cstr(&long, 0), None, "runaway length");
    }

    /// The client's high bytes are glyph indices, not errors.
    ///
    /// `Midgard\x92s armies` must survive as one string whose apostrophe is `U+0092` — the code
    /// point `bitmapfont` assigns the atlas cell at index 0x92. Rejecting the byte blanked the
    /// pane; replacing it with U+2019 would ask for a cell the atlas does not carry.
    #[test]
    fn read_cstr_keeps_cp1252_punctuation_as_its_own_glyph_index() {
        let s = read_cstr(b"Midgard\x92s armies\0", 0).expect("0x92 is text, not a parse error");
        assert_eq!(s, "Midgard\u{92}s armies");
        assert_eq!(s.chars().nth(7), Some('\u{92}'));
        assert!(
            !s.contains('\u{fffd}'),
            "lossy UTF-8 decoding would have replaced the byte"
        );
    }

    /// **Named falsifier.** Every recorded offset must be the FIRST byte of its C string.
    ///
    /// Two offsets shipped pointing mid-sentence — race 7 and race 13, the only two descriptions
    /// containing a `0x92` apostrophe, because the extractor's ASCII-only scan split the string
    /// there and recorded the tail. The panes still rendered, just without their opening clause,
    /// so every existing check stayed green. This is the observation that fails.
    #[test]
    fn every_offset_is_the_start_of_its_string() {
        let Some(root) = crate::client_dep::require_caer_client("every_offset_is_a_string_start")
        else {
            return;
        };
        let bytes = std::fs::read(root.join("game.dll")).expect("client game.dll");
        let sha = sha256_hex(&bytes);
        let builds = parse_offsets();
        let offsets = builds
            .iter()
            .find(|b| b.game_dll_sha256 == sha)
            .unwrap_or_else(|| {
                panic!(
                    "no offsets cut from build {} — the check below would be meaningless",
                    &sha[..16]
                )
            });
        for (kind, id, off) in offsets
            .race
            .iter()
            .map(|&(i, o)| ("race", i, o))
            .chain(offsets.class.iter().map(|&(i, o)| ("class", i, o)))
        {
            assert_eq!(
                bytes[off - 1],
                0,
                "{kind} {id} at {off:#x} is preceded by {:#04x}, not NUL — the offset is \
                 mid-string and the pane will render with its opening clause missing",
                bytes[off - 1]
            );
        }
    }

    /// The two repaired entries, end to end through `load`.
    #[test]
    fn apostrophe_races_load_whole() {
        let Some(root) = crate::client_dep::require_caer_client("apostrophe_races_load_whole")
        else {
            return;
        };
        let t = load(&root);
        if !t.is_verified() {
            return; // different client build — `missing_client_fails_closed` covers that path
        }
        let dwarf = t.race(7).expect("Dwarf description");
        let inconnu = t.race(13).expect("Inconnu description");
        assert!(
            dwarf.starts_with("The oldest race in Midgard"),
            "Dwarf begins mid-sentence: {dwarf:.48}"
        );
        assert!(
            inconnu.starts_with("Natives of underworld"),
            "Inconnu begins mid-sentence: {inconnu:.48}"
        );
        for (name, text) in [("Dwarf", dwarf), ("Inconnu", inconnu)] {
            assert!(
                text.contains('\u{92}'),
                "{name} lost its apostrophe glyph on the way in"
            );
        }
    }
}
